require("aerial").setup({
	backends = { "lsp", "treesitter" },
	close_behavior = "global",
	width = "0.3",
	open_automatic = false,
	show_guides = true,
	filter_kind = {
		"Array",
		"Boolean",
		"Class",
		"Constant",
		"Constructor",
		"Enum",
		"EnumMember",
		"Event",
		"Field",
		"File",
		"Function",
		"Interface",
		"Key",
		"Method",
		"Module",
		"Namespace",
		"Null",
		"Number",
		"Object",
		"Operator",
		"Package",
		"Property",
		"String",
		"Struct",
		"TypeParameter",
		"Variable",
	},
})
