vim.lsp.codelens.enable()
vim.lsp.document_color.enable()
vim.lsp.inlay_hint.enable()
vim.lsp.inline_completion.enable()
vim.lsp.linked_editing_range.enable()
vim.lsp.on_type_formatting.enable()
vim.lsp.semantic_tokens.enable()

require("configs.lsp.server")
require("configs.lsp.keymap")
require("configs.lsp.diagnostic")
