# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
fpath=(~/.zmodules/zsh-completions/src $fpath)

# Created by newuser for 5.8.1
alias vim="nvim"
alias ls="lsd"

setopt autocd
setopt INC_APPEND_HISTORY_TIME

source ~/.zmodules/powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
source ~/.p10k.zsh

source ~/.zmodules/zsh-autosuggestions/zsh-autosuggestions.zsh
source ~/.zmodules/F-Sy-H/F-Sy-H.plugin.zsh

source ~/.zmodules/custom/completion.zsh
source "${HOME}/.iterm2_shell_integration.zsh"



