# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

setopt auto_cd
setopt inc_append_history_time
setopt extended_history
setopt hist_expire_dups_first
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_verify

setopt auto_pushd
setopt pushd_ignore_dups
setopt pushdminus

alias -g ...='../..'
alias -g ....='../../..'
alias -g .....='../../../..'

alias -- -='cd -'
alias l="ls -lah"
alias ll="ls -lh"
alias la="ls -lAh"

alias vim="nvim"
alias ls="lsd"

source "${ZSH_MODULES_DIR}/powerlevel10k/powerlevel10k.zsh-theme"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

fpath=(${ZSH_MODULES_DIR}/zsh-completions/src $fpath)
source "${ZSH_MODULES_DIR}/zsh-autosuggestions/zsh-autosuggestions.zsh"
source "${ZSH_MODULES_DIR}/F-Sy-H/F-Sy-H.plugin.zsh"

source "${ZSH_MODULES_DIR}/custom/completion.zsh"


source "${HOME}/.iterm2_shell_integration.zsh"

