{% macro main(rule) %}
# > Netflix
USER-AGENT,Argo*,{{ rule }}
DOMAIN-SUFFIX,netflix.com,{{ rule }}
DOMAIN-SUFFIX,netflix.net,{{ rule }}
DOMAIN-SUFFIX,nflxext.com,{{ rule }}
DOMAIN-SUFFIX,nflximg.com,{{ rule }}
DOMAIN-SUFFIX,nflximg.net,{{ rule }}
DOMAIN-SUFFIX,nflxso.net,{{ rule }}
DOMAIN-SUFFIX,nflxvideo.net,{{ rule }}
DOMAIN-SUFFIX,netflixdnstest0.com,{{ rule }}
DOMAIN-SUFFIX,netflixdnstest1.com,{{ rule }}
DOMAIN-SUFFIX,netflixdnstest2.com,{{ rule }}
DOMAIN-SUFFIX,netflixdnstest3.com,{{ rule }}
DOMAIN-SUFFIX,netflixdnstest4.com,{{ rule }}
DOMAIN-SUFFIX,netflixdnstest5.com,{{ rule }}
DOMAIN-SUFFIX,netflixdnstest6.com,{{ rule }}
DOMAIN-SUFFIX,netflixdnstest7.com,{{ rule }}
DOMAIN-SUFFIX,netflixdnstest8.com,{{ rule }}
DOMAIN-SUFFIX,netflixdnstest9.com,{{ rule }}
IP-CIDR,23.246.0.0/18,{{ rule }},no-resolve
IP-CIDR,37.77.184.0/21,{{ rule }},no-resolve
IP-CIDR,45.57.0.0/17,{{ rule }},no-resolve
IP-CIDR,64.120.128.0/17,{{ rule }},no-resolve
IP-CIDR,66.197.128.0/17,{{ rule }},no-resolve
IP-CIDR,108.175.32.0/20,{{ rule }},no-resolve
IP-CIDR,192.173.64.0/18,{{ rule }},no-resolve
IP-CIDR,198.38.96.0/19,{{ rule }},no-resolve
IP-CIDR,198.45.48.0/20,{{ rule }},no-resolve

{% endmacro %}